export const EPISODES = [
  { season: 1, title: 'Encounter at Farpoint' },
  { season: 1, title: 'The Naked Now' },
  { season: 1, title: 'Code of Honor' },
  { season: 1, title: 'The Last Outpost' },
  { season: 1, title: 'Where No One Has Gone Before' },
  { season: 1, title: 'Lonely Among Us' },
  { season: 1, title: 'Justice' },
  { season: 1, title: 'The Battle' },
  { season: 1, title: 'Hide and Q' },
  { season: 1, title: 'Haven' },
  { season: 1, title: 'The Big Goodbye' },
  { season: 1, title: 'Datalore' },
  { season: 1, title: 'Angel One' },
  { season: 1, title: '11001001' },
  { season: 1, title: 'Too Short a Season' },
  { season: 1, title: 'When the Bough Breaks' },
  { season: 1, title: 'Home Soil' },
  { season: 1, title: 'Coming of Age' },
  { season: 1, title: 'Heart of Glory' },
  { season: 1, title: 'The Arsenal of Freedom' },
  { season: 1, title: 'Symbiosis' },
  { season: 1, title: 'Skin of Evil' },
  { season: 1, title: "We'll Always Have Paris" },
  { season: 1, title: 'Conspiracy' },
  { season: 1, title: 'The Neutral Zone' },
  { season: 2, title: 'The Child' },
  { season: 2, title: 'Where Silence Has Lease' },
  { season: 2, title: 'Elementary, Dear Data' },
  { season: 2, title: 'The Outrageous Okona' },
  { season: 2, title: 'Loud as a Whisper' },
  { season: 2, title: 'The Schizoid Man' },
  { season: 2, title: 'Unnatural Selection' },
  { season: 2, title: 'A Matter of Honor' },
  { season: 2, title: 'The Measure of a Man' },
  { season: 2, title: 'The Dauphin' },
  { season: 2, title: 'Contagion' },
  { season: 2, title: 'The Royale' },
  { season: 2, title: 'Time Squared' },
  { season: 2, title: 'The Icarus Factor' },
  { season: 2, title: 'Pen Pals' },
  { season: 2, title: 'Q Who' },
  { season: 2, title: 'Samaritan Snare' },
  { season: 2, title: 'Up the Long Ladder' },
  { season: 2, title: 'Manhunt' },
  { season: 2, title: 'The Emissary' },
  { season: 2, title: 'Peak Performance' },
  { season: 2, title: 'Shades of Gray' },
  { season: 3, title: 'Evolution' },
  { season: 3, title: 'The Ensigns of Command' },
  { season: 3, title: 'The Survivors' },
  { season: 3, title: 'Who Watches the Watchers' },
  { season: 3, title: 'The Bonding' },
  { season: 3, title: 'Booby Trap' },
  { season: 3, title: 'The Enemy' },
  { season: 3, title: 'The Price' },
  { season: 3, title: 'The Vengeance Factor' },
  { season: 3, title: 'The Defector' },
  { season: 3, title: 'The Hunted' },
  { season: 3, title: 'The High Ground' },
  { season: 3, title: 'Déjà Q' },
  { season: 3, title: 'A Matter of Perspective' },
  { season: 3, title: "Yesterday's Enterprise" },
  { season: 3, title: 'The Offspring' },
  { season: 3, title: 'Sins of the Father' },
  { season: 3, title: 'Allegiance' },
  { season: 3, title: "Captain's Holiday" },
  { season: 3, title: 'Tin Man' },
  { season: 3, title: 'Hollow Pursuits' },
  { season: 3, title: 'The Most Toys' },
  { season: 3, title: 'Sarek' },
  { season: 3, title: 'Ménage à Troi' },
  { season: 3, title: 'Transfigurations' },
  { season: 3, title: 'The Best of Both Worlds, Part I' },
  { season: 4, title: 'The Best of Both Worlds, Part II' },
  { season: 4, title: 'Family' },
  { season: 4, title: 'Brothers' },
  { season: 4, title: 'Suddenly Human' },
  { season: 4, title: 'Remember Me' },
  { season: 4, title: 'Legacy' },
  { season: 4, title: 'Reunion' },
  { season: 4, title: 'Future Imperfect' },
  { season: 4, title: 'Final Mission' },
  { season: 4, title: 'The Loss' },
  { season: 4, title: "Data's Day" },
  { season: 4, title: 'The Wounded' },
  { season: 4, title: "Devil's Due" },
  { season: 4, title: 'Clues' },
  { season: 4, title: 'First Contact' },
  { season: 4, title: "Galaxy's Child" },
  { season: 4, title: 'Night Terrors' },
  { season: 4, title: 'Identity Crisis' },
  { season: 4, title: 'The Nth Degree' },
  { season: 4, title: 'Qpid' },
  { season: 4, title: 'The Drumhead' },
  { season: 4, title: 'Half a Life' },
  { season: 4, title: 'The Host' },
  { season: 4, title: "The Mind's Eye" },
  { season: 4, title: 'In Theory' },
  { season: 4, title: 'Redemption, Part I' },
  { season: 5, title: 'Redemption, Part II' },
  { season: 5, title: 'Darmok' },
  { season: 5, title: 'Ensign Ro' },
  { season: 5, title: 'Silicon Avatar' },
  { season: 5, title: 'Disaster' },
  { season: 5, title: 'The Game' },
  { season: 5, title: 'Unification, Part I' },
  { season: 5, title: 'Unification, Part II' },
  { season: 5, title: 'A Matter of Time' },
  { season: 5, title: 'New Ground' },
  { season: 5, title: 'Hero Worship' },
  { season: 5, title: 'Violations' },
  { season: 5, title: 'The Masterpiece Society' },
  { season: 5, title: 'Conundrum' },
  { season: 5, title: 'Power Play' },
  { season: 5, title: 'Ethics' },
  { season: 5, title: 'The Outcast' },
  { season: 5, title: 'Cause and Effect' },
  { season: 5, title: 'The First Duty' },
  { season: 5, title: 'Cost of Living' },
  { season: 5, title: 'The Perfect Mate' },
  { season: 5, title: 'Imaginary Friend' },
  { season: 5, title: 'I, Borg' },
  { season: 5, title: 'The Next Phase' },
  { season: 5, title: 'The Inner Light' },
  { season: 5, title: "Time's Arrow, Part I" },
  { season: 6, title: "Time's Arrow, Part II" },
  { season: 6, title: 'Realm of Fear' },
  { season: 6, title: 'Man of the People' },
  { season: 6, title: 'Relics' },
  { season: 6, title: 'Schisms' },
  { season: 6, title: 'True Q' },
  { season: 6, title: 'Rascals' },
  { season: 6, title: 'A Fistful of Datas' },
  { season: 6, title: 'The Quality of Life' },
  { season: 6, title: 'Chain of Command, Part I' },
  { season: 6, title: 'Chain of Command, Part II' },
  { season: 6, title: 'Ship in a Bottle' },
  { season: 6, title: 'Aquiel' },
  { season: 6, title: 'Face of the Enemy' },
  { season: 6, title: 'Tapestry' },
  { season: 6, title: 'Birthright, Part I' },
  { season: 6, title: 'Birthright, Part II' },
  { season: 6, title: 'Starship Mine' },
  { season: 6, title: 'Lessons' },
  { season: 6, title: 'The Chase' },
  { season: 6, title: 'Frame of Mind' },
  { season: 6, title: 'Suspicions' },
  { season: 6, title: 'Rightful Heir' },
  { season: 6, title: 'Second Chances' },
  { season: 6, title: 'Timescape' },
  { season: 6, title: 'Descent, Part I' },
  { season: 7, title: 'Descent, Part II' },
  { season: 7, title: 'Liaisons' },
  { season: 7, title: 'Interface' },
  { season: 7, title: 'Gambit, Part I' },
  { season: 7, title: 'Gambit, Part II' },
  { season: 7, title: 'Phantasms' },
  { season: 7, title: 'Dark Page' },
  { season: 7, title: 'Attached' },
  { season: 7, title: 'Force of Nature' },
  { season: 7, title: 'Inheritance' },
  { season: 7, title: 'Parallels' },
  { season: 7, title: 'The Pegasus' },
  { season: 7, title: 'Homeward' },
  { season: 7, title: 'Sub Rosa' },
  { season: 7, title: 'Lower Decks' },
  { season: 7, title: 'Thine Own Self' },
  { season: 7, title: 'Masks' },
  { season: 7, title: 'Eye of the Beholder' },
  { season: 7, title: 'Genesis' },
  { season: 7, title: "Journey's End" },
  { season: 7, title: 'Firstborn' },
  { season: 7, title: 'Bloodlines' },
  { season: 7, title: 'Emergence' },
  { season: 7, title: 'Preemptive Strike' },
  { season: 7, title: 'All Good Things...' },
]
